- name: create directory /home/backup/mysql
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: 0744
  no_log: true


- name: Create MySQL backup user
  mysql_user:
    name: "{{ mysql_backup_user }}"
    password: "{{ mysql_backup_pass }}"
    priv: "{{ mysql_database }}.*:SELECT,LOCK TABLES"
    host: "localhost"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true   


- name: Copy MySQL configuration file
  template:
    src: backup.my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: 0700
  no_log: true 


- name: Copy mysql cron
  template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
    owner: root
    group: root
    mode: 0755
  no_log: true
