- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  no_log: true 


- name: Index
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    follow: no
  no_log: true 


- name: Nginx as frontend, Nginx configuration, add Prometheus ports
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    mode: '0644'
  no_log: true 
  notify: Restart nginx


- name: Start and enable nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes  


- name: Start nginx
  service:
    name: nginx
    state: started
