- name: Add influx and telegraf key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key


- name: Add influx and telegraf repository into sources list
  apt_repository:
    repo: deb https://repos.influxdata.com/debian focal stable
  no_log: true 


- name: Install 'influxdb'
  apt:
    name: influxdb
  no_log: true 


- name: Ensure influxdb is running
  service:
    name: influxdb
    state: started
    enabled: yes


- name: Install 'telegraf'
  apt:
    name: telegraf
  no_log: true 
  

- name: Ensure Telegraf is running
  service:
    name: telegraf
    state: started
    enabled: yes


- name: Copy influxdb.conf.j2 into /etc/influxdb/
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  no_log: true 
  notify: Restart influxdb


- name: Copy telegraf.conf.j2 into /etc/telegraf/telegraf.conf.j2
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  no_log: true 
  notify: Restart telegraf


- name: Execute handlers preemptively
  meta: flush_handlers
