# config file version
apiVersion: 1

datasources:
 - name: prometheus
   type: prometheus
   url: http://prometheus:{{prometheus_port}}/prometheus    
   password:
   user:
   database:
   isDefault: true
   editable: true

 - name: InfluxDB
   type: influxdb
   url: http://influxdb:{{ influxdb_port }}
   password:
   user:
   database: latency
   editable: true

 - name: InfluxDB-telegraf
   type: influxdb
   url: http://influxdb:{{ influxdb_port }}
   password:
   user:
   database: telegraf
   editable: true

 - name: InfluxDB-latency
   type: influxdb
   url: http://influxdb:{{ pinger_port }}
   password:
   user:
   database: latency
   editable: true
