- name: install prometheus node exporter
  apt:
    name: prometheus-node-exporter
  no_log: true 

- name: Verify prometheus node exporter service
  service:
    name: prometheus-node-exporter
    state: started
    enabled: true
  no_log: true
 