- name: install prometheus
  apt:
    name: prometheus
  no_log: true 


- name: copy prometheus.yml.j2 template
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  no_log: true 
  notify: Restart prometheus


- name: copy prometheus.j2 template
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  no_log: true 
  notify: Restart prometheus
